export const HOTKEYS = {
    KEY_A_PREV_CLASS : 65,
    KEY_D_NEXT_CLASS : 68,
    KEY_G_LASSO_ERASER: 71,
    KEY_H_HIDE_OTHERS: 72,
    KEY_L_TOGGLE_BORDERS: 76,
    KEY_P_PAN : 80,
    KEY_E_ERASER: 69,
    KEY_B_BRUSH: 66,
    KEY_F_FILL_BRUSH: 70,
    KEY_V_FILL_VECTOR: 86,
    KEY_CTRL_Z_UNDO: 90,
    KEY_CTRL_Y_REDO: 89,
    KEY_K_PICKKER: 75,
    KEY_M_FLIP: 77,
    KEY_O_VIEW_ALL: 79,
    KEY_T_PRETREATMENTS: 84,
    KEY_CTRL_S_SAVE: 83
};
